name: Fetch Events and Generate Website

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  fetch-and-generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Fetch events from Google Calendar
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
      run: |
        node automation/fetch-events.js

    - name: Generate static website
      run: |
        node automation/generate-website.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./src
